### ISSUE TITLE
请问源代码什么时候可以放出ovo

### ISSUE THREAD

**Issue by awei669** [fubinfb/MSD-Font#1]

**Comment by fubinfb** [comment]
我们争取在两周内放出文章的代码。另外，我们的数据库是按照[FFG-benchmarks](https://github.com/clovaai/fewshot-font-generation)制作的，您可以先将您的数据准备好。

**Comment by fubinfb** [comment]
由于前期其它事情耽搁，我正在抓紧整理代码，请您再等1-2天。非常抱歉

**Comment by fubinfb** [comment]
我们已经开源了所有代码~

**Comment by awei669** [comment]
感谢^ - ^
 we1pan
 ***@***.***
  
---- 回复的原邮件 ----
发件人 Fu Bin ***@***.***> 发送日期 2024年07月09日 19:17 收件人 fubinfb/MSD-Font ***@***.***> 抄送人 Wei Pan ***@***.***>,
Author ***@***.***> 主题 Re: [fubinfb/MSD-Font] 请问源代码什么时候可以放出ovo (Issue #1)  

我们已经开源了所有代码~
