### ISSUE TITLE
Inquiry about Required Compute Resources

### ISSUE THREAD

**Issue by klevin-ken** [fubinfb/MSD-Font#2]
Hello,

I am interested in using this project and would like to know more about the required compute resources.

**Comment by fubinfb** [comment]
In this paper, we train our model on a single 3090 GPU for training stage one, and use two 3090 GPU for training stage two. 
It is worthy to mention that, we will release the code for training stage two before 2024. 07. 14.

**Comment by klevin-ken** [comment]
Thanks!

**Comment by fubinfb** [comment]
Hi, we have released all our code.

**Comment by positive-man** [comment]
> In this paper, we train our model on a single 3090 GPU for training stage one, and use two 3090 GPU for training stage two. It is worthy to mention that, we will release the code for training stage two before 2024. 07. 14.

你好，请问训练时间大概多久？
