### ISSUE TITLE
关于数据集图像的小问题

### ISSUE THREAD

**Issue by positive-man** [fubinfb/MSD-Font#4]
您好，我是一个小白，想问一个和程序无关的问题。请问为什么要用三通道的rgb图像，而不用单通道的灰度图像？这两个肉眼看起来好像没啥区别。。。用三通道的图像效果会更好吗？如果改成单通道的灰度图像会不会训练得更快些？

**Comment by fubinfb** [comment]
We use the SD pretrained VAE to project images into latent space, and the input for VAE encoder must be RGB image.

**Comment by positive-man** [comment]
> We use the SD pretrained VAE to project images into latent space, and the input for VAE encoder must be RGB image.

好的，感谢
