### ISSUE TITLE
can each stage be individually evaluated, the scripts seems to just start training again, if we run the eval script for each stage given in config folder

### ISSUE THREAD

**Issue by avinash-thakur-monotype-ai** [fubinfb/MSD-Font#5]

**Comment by fubinfb** [comment]
which script？

**Comment by fubinfb** [comment]
the eval script provided in this project is used for evaluating the final stage model

**Comment by fubinfb** [comment]
You can modify the eval script to eval the Stage 1-2 model. 
(maybe you need check the setting of diffusion steps, the model must cover all steps, if you want to eval it)

**Comment by avinash-thakur-monotype-ai** [comment]
![image (19)](https://github.com/user-attachments/assets/f255d920-65f3-48af-9ec0-49ac0617d917)
![image (20)](https://github.com/user-attachments/assets/f8769d88-c096-4494-a9b4-52ad8fd8a1b1)

the logs which we visualize on tensorboard is confusing, the images being shown are perfect from first step itslef
<img width="925" alt="Screenshot 2024-10-16 at 2 56 59 PM" src="https://github.com/user-attachments/assets/d3f2c513-5dde-49b2-b638-128f971a08f6">

**Comment by fubinfb** [comment]
this is the reconstruction img. only vae encode and then vae decode, directly

**Comment by avinash-thakur-monotype-ai** [comment]
Thank you . it cleared my doubts.
